"""
Pydantic schemas for structured data throughout the audio agent framework.

These schemas define explicit contracts between components.
All schemas use Pydantic v2 with strict validation.
"""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, model_validator


# =============================================================================
# Enums
# =============================================================================

class PlannerActionType(str, Enum):
    """
    Actions the planner can decide to take.
    
    - ANSWER: Signal readiness for final answer generation by the frontend model
    - CALL_TOOL: Invoke a tool to gather more evidence
    - CLARIFY_INTENT: Clarify the user's intent and expected output format
    - FAIL: Stop with explicit failure (unrecoverable state)
    """
    ANSWER = "answer"
    CALL_TOOL = "call_tool"
    CLARIFY_INTENT = "clarify_intent"
    FAIL = "fail"


# =============================================================================
# Frontend Schemas
# =============================================================================

class FrontendInput(BaseModel):
    """Input to the frontend module."""
    question: str = Field(..., min_length=1, description="User question about the audio")
    audio_paths: list[str] = Field(..., min_length=1, description="One or more audio file paths")
    
    @model_validator(mode="after")
    def validate_audio_paths(self) -> "FrontendInput":
        """Validate that at least one audio path is provided and all exist."""
        if not self.audio_paths:
            raise ValueError("At least one audio path must be provided")
        for path in self.audio_paths:
            if not path or not path.strip():
                raise ValueError("Audio paths cannot be empty strings")
        return self


class FrontendOutput(BaseModel):
    """
    Output from the frontend module.
    
    The frontend (LALM) produces question-guided initial evidence.
    This output is intentionally lightweight for downstream planning, not final answering.
    """
    question_guided_caption: str = Field(
        ...,
        min_length=1,
        description="Concise caption focused on information relevant to the user question",
    )
    timestamp: datetime = Field(default_factory=datetime.now)
    model_config = {"extra": "forbid"}

    @model_validator(mode="after")
    def validate_frontend_output(self) -> "FrontendOutput":
        """Fail-fast validation for frontend output structure."""
        if not self.question_guided_caption.strip():
            raise ValueError("question_guided_caption must be non-empty after stripping")

        return self


# =============================================================================
# Evidence Schemas
# =============================================================================

class EvidenceItem(BaseModel):
    """
    A single piece of evidence accumulated during agent execution.
    
    Evidence can come from the frontend, tools, or fusion operations.
    """
    source: str = Field(..., description="Source of this evidence (frontend, tool name, etc.)")
    content: str = Field(..., description="The evidence content")
    evidence_type: str = Field(default="text", description="Type of evidence: text, structured, etc.")
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    metadata: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.now)


class AudioItem(BaseModel):
    """
    Represents an audio file in the agent's audio list.
    
    Tracks both original input audio and audio files generated by tools
    (e.g., separated sources, enhanced audio, segments).
    """
    audio_id: str = Field(..., description="Unique identifier (e.g., audio_0, audio_1)")
    path: str = Field(..., description="Path to the audio file")
    source: str = Field(..., description="Source: 'original' or tool name that generated it")
    description: str = Field(..., description="Human-readable description of what this audio represents")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    timestamp: datetime = Field(default_factory=datetime.now)
    model_config = {"extra": "forbid"}

    @model_validator(mode="after")
    def validate_audio_item(self) -> "AudioItem":
        """Fail-fast validation for audio item."""
        if not self.audio_id.strip():
            raise ValueError("audio_id must be non-empty")
        if not self.path.strip():
            raise ValueError("path must be non-empty")
        if not self.description.strip():
            raise ValueError("description must be non-empty")
        return self


# =============================================================================
# Tool Schemas
# =============================================================================

class ToolSpec(BaseModel):
    """
    Specification of a tool, exposed to the planner for decision-making.
    
    This is a planner-friendly view of a tool's capabilities.
    """
    name: str = Field(..., min_length=1, description="Unique tool identifier")
    description: str = Field(..., description="What this tool does")
    input_schema: dict[str, Any] = Field(default_factory=dict, description="Expected input format")
    output_schema: dict[str, Any] = Field(default_factory=dict, description="Expected output format")
    tags: list[str] = Field(default_factory=list, description="Tags for categorization")


class ToolCallRequest(BaseModel):
    """Request to invoke a tool."""
    tool_name: str = Field(..., min_length=1)
    args: dict[str, Any] = Field(default_factory=dict)
    context: dict[str, Any] = Field(default_factory=dict, description="Optional context for the tool")


class ToolResult(BaseModel):
    """Result returned by a tool after execution."""
    tool_name: str = Field(...)
    success: bool = Field(...)
    output: dict[str, Any] = Field(default_factory=dict, description="Structured output from the tool")
    error_message: str | None = Field(default=None)
    execution_time_ms: float = Field(default=0.0)
    timestamp: datetime = Field(default_factory=datetime.now)


class ToolCallRecord(BaseModel):
    """
    Record of a tool call for history tracking.
    
    Stores both the request and result together.
    """
    request: ToolCallRequest
    result: ToolResult
    step_number: int = Field(ge=0)


# =============================================================================
# Planner Schemas
# =============================================================================

class PlannerInput(BaseModel):
    """
    Input provided to the planner for decision-making.
    
    This is a structured view of the current agent state.
    """
    question: str
    evidence_log: list[EvidenceItem]
    tool_call_history: list[ToolCallRecord]
    available_tools: list[ToolSpec]
    step_count: int
    max_steps: int


class ExecutionStep(BaseModel):
    """
    A single step in the execution plan.
    
    Part of InitialPlan.detailed_plan for complex questions requiring multi-step reasoning.
    """
    step_number: int = Field(..., ge=1, description="Step order (1, 2, 3...)")
    description: str = Field(..., min_length=1, description="What this step does")
    tool_type: str | None = Field(default=None, description="Suggested tool type (e.g., 'asr', 'diarization')")
    expected_output: str | None = Field(default=None, description="What we expect from this step")
    
    model_config = {"extra": "forbid"}
    
    @model_validator(mode="after")
    def validate_step(self) -> "ExecutionStep":
        """Fail-fast validation for execution step."""
        if not self.description.strip():
            raise ValueError("ExecutionStep.description must be non-empty")
        return self


class InitialPlan(BaseModel):
    """
    Initial high-level plan generated from the question only.

    This plan guides downstream action decisions but is not itself a tool call decision.
    Includes clarified intent, expected output format, and optional detailed execution steps.
    """

    approach: str = Field(..., min_length=1, description="High-level strategy for answering")
    focus_points: list[str] = Field(
        default_factory=list,
        description="Key aspects to focus on while gathering evidence",
    )
    possible_tool_types: list[str] = Field(
        default_factory=list,
        description="Possible tool categories that may help later",
    )
    notes: str | None = Field(default=None, description="Optional concise planning notes")
    clarified_intent: str | None = Field(
        default=None,
        description="What the question is actually asking (extracted from question)",
    )
    expected_output_format: str | None = Field(
        default=None,
        description="Expected format of the final answer (extracted from question)",
    )
    requires_audio_output: bool = Field(
        default=False,
        description="Whether the task requires/produces an audio file as output",
    )
    detailed_plan: list[ExecutionStep] = Field(
        default_factory=list,
        description="Optional todo list for complex questions. Leave empty for simple questions.",
    )
    timestamp: datetime = Field(default_factory=datetime.now)
    model_config = {"extra": "forbid"}

    @model_validator(mode="after")
    def validate_plan(self) -> "InitialPlan":
        """Fail-fast validation for planning output."""
        if not self.approach.strip():
            raise ValueError("InitialPlan.approach must be non-empty after stripping")
        for item in self.focus_points:
            if not item or not item.strip():
                raise ValueError("InitialPlan.focus_points cannot contain empty strings")
        for item in self.possible_tool_types:
            if not item or not item.strip():
                raise ValueError("InitialPlan.possible_tool_types cannot contain empty strings")
        return self


class PlannerDecision(BaseModel):
    """
    Decision made by the planner.
    
    Validation ensures consistency:
    - CALL_TOOL requires selected_tool_name and selected_audio_id
    - ANSWER no longer requires draft_answer (the frontend model generates the final answer)
    """
    action: PlannerActionType
    rationale: str = Field(..., min_length=1, description="Explanation for the decision")
    selected_tool_name: str | None = Field(default=None)
    selected_tool_args: dict[str, Any] = Field(default_factory=dict)
    selected_audio_id: str | None = Field(
        default=None,
        description="Audio ID to use for tool call (required for CALL_TOOL)"
    )
    draft_answer: str | None = Field(default=None)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=datetime.now)
    model_config = {"extra": "forbid"}

    @model_validator(mode="after")
    def validate_action_consistency(self) -> "PlannerDecision":
        """Ensure action-specific fields are populated."""
        if self.action == PlannerActionType.CALL_TOOL:
            if not self.selected_tool_name:
                raise ValueError(
                    "PlannerDecision with action=CALL_TOOL must have non-empty selected_tool_name"
                )
            if not self.selected_audio_id:
                raise ValueError(
                    "PlannerDecision with action=CALL_TOOL must have non-empty selected_audio_id"
                )
        # ANSWER no longer requires draft_answer (frontend generates final answer)
        # CLARIFY_INTENT and FAIL require no additional fields - uses rationale only
        return self


# =============================================================================
# Format Check Schema
# =============================================================================

class FormatCheckResult(BaseModel):
    """
    Result of checking the proposed answer against format requirements.
    
    The format check ensures the answer follows the expected output format
    without evaluating the content correctness (which is done by verification).
    """
    passed: bool = Field(
        ...,
        description="True if format check passed, False if format violations detected"
    )
    critique: str | None = Field(
        default=None,
        description="Explanation of format violations if failed, null if passed"
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Confidence in the format check assessment"
    )
    timestamp: datetime = Field(default_factory=datetime.now)
    model_config = {"extra": "forbid"}


# =============================================================================
# Audio Output Schema
# =============================================================================

class AudioOutput(BaseModel):
    """Output audio file information for final answer."""
    audio_id: str = Field(..., description="Reference ID (e.g., audio_3)")
    path: str = Field(..., description="Absolute path to the audio file")
    description: str = Field(..., description="Description of what this audio represents")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    
    model_config = {"extra": "forbid"}


# =============================================================================
# Final Answer Schema
# =============================================================================

class FinalAnswer(BaseModel):
    """The final answer produced by the agent."""
    answer: str = Field(..., min_length=1)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    evidence_summary: str = Field(default="")
    reasoning_trace: str = Field(default="")
    output_audio: AudioOutput | None = Field(
        default=None,
        description="Output audio file if the task produces one",
    )
    timestamp: datetime = Field(default_factory=datetime.now)
